// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_Body
#define IOD_SYMBOL_Body
    iod_define_symbol(Body)
#endif

#ifndef IOD_SYMBOL_Status
#define IOD_SYMBOL_Status
    iod_define_symbol(Status)
#endif

#ifndef IOD_SYMBOL_address
#define IOD_SYMBOL_address
    iod_define_symbol(address)
#endif

#ifndef IOD_SYMBOL_age
#define IOD_SYMBOL_age
    iod_define_symbol(age)
#endif

#ifndef IOD_SYMBOL_auto_increment
#define IOD_SYMBOL_auto_increment
    iod_define_symbol(auto_increment)
#endif

#ifndef IOD_SYMBOL_before_create
#define IOD_SYMBOL_before_create
    iod_define_symbol(before_create)
#endif

#ifndef IOD_SYMBOL_blocking
#define IOD_SYMBOL_blocking
    iod_define_symbol(blocking)
#endif

#ifndef IOD_SYMBOL_broadcast
#define IOD_SYMBOL_broadcast
    iod_define_symbol(broadcast)
#endif

#ifndef IOD_SYMBOL_city
#define IOD_SYMBOL_city
    iod_define_symbol(city)
#endif

#ifndef IOD_SYMBOL_computed
#define IOD_SYMBOL_computed
    iod_define_symbol(computed)
#endif

#ifndef IOD_SYMBOL_con
#define IOD_SYMBOL_con
    iod_define_symbol(con)
#endif

#ifndef IOD_SYMBOL_echo
#define IOD_SYMBOL_echo
    iod_define_symbol(echo)
#endif

#ifndef IOD_SYMBOL_email
#define IOD_SYMBOL_email
    iod_define_symbol(email)
#endif

#ifndef IOD_SYMBOL_filename
#define IOD_SYMBOL_filename
    iod_define_symbol(filename)
#endif

#ifndef IOD_SYMBOL_from
#define IOD_SYMBOL_from
    iod_define_symbol(from)
#endif

#ifndef IOD_SYMBOL_get_id
#define IOD_SYMBOL_get_id
    iod_define_symbol(get_id)
#endif

#ifndef IOD_SYMBOL_get_user
#define IOD_SYMBOL_get_user
    iod_define_symbol(get_user)
#endif

#ifndef IOD_SYMBOL_hello
#define IOD_SYMBOL_hello
    iod_define_symbol(hello)
#endif

#ifndef IOD_SYMBOL_hello_world
#define IOD_SYMBOL_hello_world
    iod_define_symbol(hello_world)
#endif

#ifndef IOD_SYMBOL_id
#define IOD_SYMBOL_id
    iod_define_symbol(id)
#endif

#ifndef IOD_SYMBOL_js_client
#define IOD_SYMBOL_js_client
    iod_define_symbol(js_client)
#endif

#ifndef IOD_SYMBOL_json
#define IOD_SYMBOL_json
    iod_define_symbol(json)
#endif

#ifndef IOD_SYMBOL_login
#define IOD_SYMBOL_login
    iod_define_symbol(login)
#endif

#ifndef IOD_SYMBOL_logout
#define IOD_SYMBOL_logout
    iod_define_symbol(logout)
#endif

#ifndef IOD_SYMBOL_message
#define IOD_SYMBOL_message
    iod_define_symbol(message)
#endif

#ifndef IOD_SYMBOL_module
#define IOD_SYMBOL_module
    iod_define_symbol(module)
#endif

#ifndef IOD_SYMBOL_my_scope
#define IOD_SYMBOL_my_scope
    iod_define_symbol(my_scope)
#endif

#ifndef IOD_SYMBOL_my_tracking_id
#define IOD_SYMBOL_my_tracking_id
    iod_define_symbol(my_tracking_id)
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    iod_define_symbol(name)
#endif

#ifndef IOD_SYMBOL_nick
#define IOD_SYMBOL_nick
    iod_define_symbol(nick)
#endif

#ifndef IOD_SYMBOL_non_blocking
#define IOD_SYMBOL_non_blocking
    iod_define_symbol(non_blocking)
#endif

#ifndef IOD_SYMBOL_nthreads
#define IOD_SYMBOL_nthreads
    iod_define_symbol(nthreads)
#endif

#ifndef IOD_SYMBOL_on_close
#define IOD_SYMBOL_on_close
    iod_define_symbol(on_close)
#endif

#ifndef IOD_SYMBOL_on_destroy_success
#define IOD_SYMBOL_on_destroy_success
    iod_define_symbol(on_destroy_success)
#endif

#ifndef IOD_SYMBOL_on_open
#define IOD_SYMBOL_on_open
    iod_define_symbol(on_open)
#endif

#ifndef IOD_SYMBOL_password
#define IOD_SYMBOL_password
    iod_define_symbol(password)
#endif

#ifndef IOD_SYMBOL_pm
#define IOD_SYMBOL_pm
    iod_define_symbol(pm)
#endif

#ifndef IOD_SYMBOL_post_encoding
#define IOD_SYMBOL_post_encoding
    iod_define_symbol(post_encoding)
#endif

#ifndef IOD_SYMBOL_primary_key
#define IOD_SYMBOL_primary_key
    iod_define_symbol(primary_key)
#endif

#ifndef IOD_SYMBOL_read_only
#define IOD_SYMBOL_read_only
    iod_define_symbol(read_only)
#endif

#ifndef IOD_SYMBOL_scope
#define IOD_SYMBOL_scope
    iod_define_symbol(scope)
#endif

#ifndef IOD_SYMBOL_sess
#define IOD_SYMBOL_sess
    iod_define_symbol(sess)
#endif

#ifndef IOD_SYMBOL_set_id
#define IOD_SYMBOL_set_id
    iod_define_symbol(set_id)
#endif

#ifndef IOD_SYMBOL_signin
#define IOD_SYMBOL_signin
    iod_define_symbol(signin)
#endif

#ifndef IOD_SYMBOL_signout
#define IOD_SYMBOL_signout
    iod_define_symbol(signout)
#endif

#ifndef IOD_SYMBOL_signup
#define IOD_SYMBOL_signup
    iod_define_symbol(signup)
#endif

#ifndef IOD_SYMBOL_song
#define IOD_SYMBOL_song
    iod_define_symbol(song)
#endif

#ifndef IOD_SYMBOL_stream
#define IOD_SYMBOL_stream
    iod_define_symbol(stream)
#endif

#ifndef IOD_SYMBOL_synchronous
#define IOD_SYMBOL_synchronous
    iod_define_symbol(synchronous)
#endif

#ifndef IOD_SYMBOL_test
#define IOD_SYMBOL_test
    iod_define_symbol(test)
#endif

#ifndef IOD_SYMBOL_test1
#define IOD_SYMBOL_test1
    iod_define_symbol(test1)
#endif

#ifndef IOD_SYMBOL_test2
#define IOD_SYMBOL_test2
    iod_define_symbol(test2)
#endif

#ifndef IOD_SYMBOL_test3
#define IOD_SYMBOL_test3
    iod_define_symbol(test3)
#endif

#ifndef IOD_SYMBOL_test4
#define IOD_SYMBOL_test4
    iod_define_symbol(test4)
#endif

#ifndef IOD_SYMBOL_test5
#define IOD_SYMBOL_test5
    iod_define_symbol(test5)
#endif

#ifndef IOD_SYMBOL_text
#define IOD_SYMBOL_text
    iod_define_symbol(text)
#endif

#ifndef IOD_SYMBOL_title
#define IOD_SYMBOL_title
    iod_define_symbol(title)
#endif

#ifndef IOD_SYMBOL_to
#define IOD_SYMBOL_to
    iod_define_symbol(to)
#endif

#ifndef IOD_SYMBOL_upload
#define IOD_SYMBOL_upload
    iod_define_symbol(upload)
#endif

#ifndef IOD_SYMBOL_user
#define IOD_SYMBOL_user
    iod_define_symbol(user)
#endif

#ifndef IOD_SYMBOL_user_id
#define IOD_SYMBOL_user_id
    iod_define_symbol(user_id)
#endif

#ifndef IOD_SYMBOL_who_am_I
#define IOD_SYMBOL_who_am_I
    iod_define_symbol(who_am_I)
#endif

#ifndef IOD_SYMBOL_write_access
#define IOD_SYMBOL_write_access
    iod_define_symbol(write_access)
#endif

#ifndef IOD_SYMBOL_x_www_form_urlencoded
#define IOD_SYMBOL_x_www_form_urlencoded
    iod_define_symbol(x_www_form_urlencoded)
#endif

