// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_1
#define IOD_SYMBOL_1
    iod_define_number_symbol(1)
#endif

#ifndef IOD_SYMBOL_2
#define IOD_SYMBOL_2
    iod_define_number_symbol(2)
#endif

#ifndef IOD_SYMBOL_auto_increment
#define IOD_SYMBOL_auto_increment
    iod_define_symbol(auto_increment)
#endif

#ifndef IOD_SYMBOL_before_create
#define IOD_SYMBOL_before_create
    iod_define_symbol(before_create)
#endif

#ifndef IOD_SYMBOL_before_destroy
#define IOD_SYMBOL_before_destroy
    iod_define_symbol(before_destroy)
#endif

#ifndef IOD_SYMBOL_before_update
#define IOD_SYMBOL_before_update
    iod_define_symbol(before_update)
#endif

#ifndef IOD_SYMBOL_body
#define IOD_SYMBOL_body
    iod_define_symbol(body)
#endif

#ifndef IOD_SYMBOL_blocking
#define IOD_SYMBOL_blocking
    iod_define_symbol(blocking)
#endif
    
#ifndef IOD_SYMBOL_content_type
#define IOD_SYMBOL_content_type
    iod_define_symbol(content_type)
#endif

#ifndef IOD_SYMBOL_create
#define IOD_SYMBOL_create
    iod_define_symbol(create)
#endif

#ifndef IOD_SYMBOL_created_at
#define IOD_SYMBOL_created_at
    iod_define_symbol(created_at)
#endif

#ifndef IOD_SYMBOL_destroy
#define IOD_SYMBOL_destroy
    iod_define_symbol(destroy)
#endif

#ifndef IOD_SYMBOL_error
#define IOD_SYMBOL_error
    iod_define_symbol(error)
#endif

#ifndef IOD_SYMBOL_expires
#define IOD_SYMBOL_expires
    iod_define_symbol(expires)
#endif

#ifndef IOD_SYMBOL_get_by_id
#define IOD_SYMBOL_get_by_id
    iod_define_symbol(get_by_id)
#endif

#ifndef IOD_SYMBOL_http_api
#define IOD_SYMBOL_http_api
    iod_define_symbol(http_api)
#endif

#ifndef IOD_SYMBOL_http_delete
#define IOD_SYMBOL_http_delete
    iod_define_symbol(http_delete)
#endif

#ifndef IOD_SYMBOL_http_get
#define IOD_SYMBOL_http_get
    iod_define_symbol(http_get)
#endif

#ifndef IOD_SYMBOL_http_only
#define IOD_SYMBOL_http_only
    iod_define_symbol(http_only)
#endif

#ifndef IOD_SYMBOL_http_post
#define IOD_SYMBOL_http_post
    iod_define_symbol(http_post)
#endif

#ifndef IOD_SYMBOL_http_put
#define IOD_SYMBOL_http_put
    iod_define_symbol(http_put)
#endif

#ifndef IOD_SYMBOL_id
#define IOD_SYMBOL_id
    iod_define_symbol(id)
#endif

#ifndef IOD_SYMBOL_linux_epoll
#define IOD_SYMBOL_linux_epoll
    iod_define_symbol(linux_epoll)
#endif

#ifndef IOD_SYMBOL_methods
#define IOD_SYMBOL_methods
    iod_define_symbol(methods)
#endif

#ifndef IOD_SYMBOL_nthreads
#define IOD_SYMBOL_nthreads
    iod_define_symbol(nthreads)
#endif

#ifndef IOD_SYMBOL_on_close
#define IOD_SYMBOL_on_close
    iod_define_symbol(on_close)
#endif

#ifndef IOD_SYMBOL_on_create_success
#define IOD_SYMBOL_on_create_success
    iod_define_symbol(on_create_success)
#endif

#ifndef IOD_SYMBOL_on_destroy_success
#define IOD_SYMBOL_on_destroy_success
    iod_define_symbol(on_destroy_success)
#endif

#ifndef IOD_SYMBOL_on_open
#define IOD_SYMBOL_on_open
    iod_define_symbol(on_open)
#endif

#ifndef IOD_SYMBOL_on_update_success
#define IOD_SYMBOL_on_update_success
    iod_define_symbol(on_update_success)
#endif

#ifndef IOD_SYMBOL_one_thread_per_connection
#define IOD_SYMBOL_one_thread_per_connection
    iod_define_symbol(one_thread_per_connection)
#endif

#ifndef IOD_SYMBOL_optional
#define IOD_SYMBOL_optional
    iod_define_symbol(optional)
#endif

#ifndef IOD_SYMBOL_options
#define IOD_SYMBOL_options
    iod_define_symbol(options)
#endif

#ifndef IOD_SYMBOL_opts
#define IOD_SYMBOL_opts
    iod_define_symbol(opts)
#endif

#ifndef IOD_SYMBOL_path
#define IOD_SYMBOL_path
    iod_define_symbol(path)
#endif

#ifndef IOD_SYMBOL_primary_key
#define IOD_SYMBOL_primary_key
    iod_define_symbol(primary_key)
#endif

#ifndef IOD_SYMBOL_read_access
#define IOD_SYMBOL_read_access
    iod_define_symbol(read_access)
#endif

#ifndef IOD_SYMBOL_read_only
#define IOD_SYMBOL_read_only
    iod_define_symbol(read_only)
#endif

#ifndef IOD_SYMBOL_response
#define IOD_SYMBOL_response
    iod_define_symbol(response)
#endif

#ifndef IOD_SYMBOL_root
#define IOD_SYMBOL_root
    iod_define_symbol(root)
#endif

#ifndef IOD_SYMBOL_save
#define IOD_SYMBOL_save
    iod_define_symbol(save)
#endif

#ifndef IOD_SYMBOL_secure
#define IOD_SYMBOL_secure
    iod_define_symbol(secure)
#endif

#ifndef IOD_SYMBOL_select
#define IOD_SYMBOL_select
    iod_define_symbol(select)
#endif

#ifndef IOD_SYMBOL_silicon_ctx
#define IOD_SYMBOL_silicon_ctx
    iod_define_symbol(silicon_ctx)
#endif

#ifndef IOD_SYMBOL_silicon_root___
#define IOD_SYMBOL_silicon_root___
    iod_define_symbol(silicon_root___)
#endif

#ifndef IOD_SYMBOL_size
#define IOD_SYMBOL_size
    iod_define_symbol(size)
#endif

#ifndef IOD_SYMBOL_status
#define IOD_SYMBOL_status
    iod_define_symbol(status)
#endif

#ifndef IOD_SYMBOL_synchronous
#define IOD_SYMBOL_synchronous
    iod_define_symbol(synchronous)
#endif

#ifndef IOD_SYMBOL_update
#define IOD_SYMBOL_update
    iod_define_symbol(update)
#endif

#ifndef IOD_SYMBOL_validate
#define IOD_SYMBOL_validate
    iod_define_symbol(validate)
#endif

#ifndef IOD_SYMBOL_write_access
#define IOD_SYMBOL_write_access
    iod_define_symbol(write_access)
#endif

