// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_auto_increment
#define IOD_SYMBOL_auto_increment
    iod_define_symbol(auto_increment)
#endif

#ifndef IOD_SYMBOL_before_create
#define IOD_SYMBOL_before_create
    iod_define_symbol(before_create)
#endif

#ifndef IOD_SYMBOL_body
#define IOD_SYMBOL_body
    iod_define_symbol(body)
#endif

#ifndef IOD_SYMBOL_hello
#define IOD_SYMBOL_hello
    iod_define_symbol(hello)
#endif

#ifndef IOD_SYMBOL_id
#define IOD_SYMBOL_id
    iod_define_symbol(id)
#endif

#ifndef IOD_SYMBOL_login
#define IOD_SYMBOL_login
    iod_define_symbol(login)
#endif

#ifndef IOD_SYMBOL_logout
#define IOD_SYMBOL_logout
    iod_define_symbol(logout)
#endif

#ifndef IOD_SYMBOL_message
#define IOD_SYMBOL_message
    iod_define_symbol(message)
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    iod_define_symbol(name)
#endif

#ifndef IOD_SYMBOL_pass
#define IOD_SYMBOL_pass
    iod_define_symbol(pass)
#endif

#ifndef IOD_SYMBOL_password
#define IOD_SYMBOL_password
    iod_define_symbol(password)
#endif

#ifndef IOD_SYMBOL_post
#define IOD_SYMBOL_post
    iod_define_symbol(post)
#endif

#ifndef IOD_SYMBOL_primary_key
#define IOD_SYMBOL_primary_key
    iod_define_symbol(primary_key)
#endif

#ifndef IOD_SYMBOL_read_only
#define IOD_SYMBOL_read_only
    iod_define_symbol(read_only)
#endif

#ifndef IOD_SYMBOL_title
#define IOD_SYMBOL_title
    iod_define_symbol(title)
#endif

#ifndef IOD_SYMBOL_user
#define IOD_SYMBOL_user
    iod_define_symbol(user)
#endif

#ifndef IOD_SYMBOL_user_id
#define IOD_SYMBOL_user_id
    iod_define_symbol(user_id)
#endif

#ifndef IOD_SYMBOL_validate
#define IOD_SYMBOL_validate
    iod_define_symbol(validate)
#endif

#ifndef IOD_SYMBOL_write_access
#define IOD_SYMBOL_write_access
    iod_define_symbol(write_access)
#endif

